export {HumidityPrecipCloudGauge} from './humidityPrecipCloudGauge'
export {PressureGauge} from './pressureGauge'
export {TemperatureGauge} from './temperatureGauge'
export {UvGauge} from './uvGauge'
export {WindDirectionGauge} from './windDirectionGauge'
export {WindGauge} from './windGauge'